### ISSUE TITLE
Continued Development?

### ISSUE THREAD

**Issue by hongkongkiwi** [Grayda/ninja-allone#4]
Is development continuing with this?

I'm interested to support with some cool free geeky stuff to the developer if he can help me to keep working on this?

Also, does anybody know the difference between S10 and S20 sockets?

**Comment by Grayda** [comment]
Development sort of came to a halt when I got my Ninja Sphere and started working on a golang version (sphere-orvibo and soon, go-orvibo).

In my golang rewrite I've been improving the code which should hopefully make it back into the Ninja Blocks version. I'm still no closer to getting 433mhz sorted, but I hope to take another crack at that really soon, as I'm keen for a 433mhz "bridge" I can use with my Sphere.

I have an S10 and it seems like there isn't much difference between the 10 and the 20, asides from the design. There might be some new hardware inside, or a different way of initially pairing the sockets, but from reports I've had, the S10 and S20 use the same protocol (with some minor variations) so it all works the same, except when you get into the nitty gritty of the data tables the sockets return.

But I'm more than happy to help. Just let me know what you had in mind for this, and we'll see what we can do.

**Comment by hongkongkiwi** [comment]
I'm really keen to get my own home automation setup going, I've been considering using OpenHAB and simply adapting your driver for use with that.

I'm familiar with NodeJS so that's why I very much like the fact that the ninja-blocks driver was written in that. I have a Ninja Blocks too but I don't use it, considered getting a ninja sphere but felt the price was crazy high.

Would you mind to add your email address to your github account? I'll email you directly discuss a way in which I could help contribute to development.

How is your experience with the Sphere? Do you think it's really worth the high $320 price tag for it?

**Comment by Grayda** [comment]
Right now? No. But in the coming weeks and months it'll only get better and will certainly be worth the money. I got the chance to visit the Ninja Blocks guys in Sydney before, during and after the launch party and saw just how much stuff they've been working on, so I'm confident that it'll improve as time goes on, as they were working frantically on tons of new things.

I've enabled my email address on my profile. Let me know if it's still not showing.

**Comment by sergejey** [comment]
Hi! Just want to say thank you for your work with orvibo protocol. Really nice! I'm doing integration of Orvibo devices into MajorDoMo project (PHP based open source home automation platform) and your code really helps. I got sockets working already and almost got working allone IR blaster. It would be great to have RF part in place as well.

**Comment by Grayda** [comment]
@sergejey Just cleaning up old issues in my repos. Thought you might be interested to learn that [go-orvibo][1] has RF support now built in. You should be able to get a rough idea of how it works, even if you've never coded in Go, but the structure is very similar to the IR. 6864 [packet length] [command ID] [MAC address] [MAC address padding [RF channel ID] [two random bytes] [RF command]. Check the source though, as I may have missed something there.

Open an issue on [go-orvibo][1] if you're having troubles, and I'll look in to it. I don't own the RF switches, so this is all mostly theoretical.

[1]: http://github.com/Grayda/go-orvibo
