### ISSUE TITLE
Trouble getting running

### ISSUE THREAD

**Issue by mvaljento** [Grayda/ninja-allone#6]
First of all, thanks for building this amazing stuff for all of us. I was looking for a way to control my IR devices and after discovering your code for Ninja block, I immediately ordered my an Orvibo Allone. I'm just having a little trouble getting started, and would be very grateful for any assistance.

As instructed after setting up Allone and testing it with my devices I installed the driver on my Ninja block and sure enough it appeared in my Dashboard. If I type in LEARN in the input the Allone goes into the learning mode (red light) and apparently reads the code from my remote control (red light goes off), but there's no IR code shown in the dashboard.

Also, when I try your tests/test.js code on my Mac, i get this output first:

`==> ALLONE (11:22:1:69: Options set up`
`==> ALLONE (11:22:1:83: Binding client socket using Unix method`

Then after about 30-60 seconds I get this:

`==> ALLONE (11:22:41:72: Client socket: Message received from: 192.168.1.165. Message is: 686400067161`
`Message received from: 192.168.1.165. Was: 686400067161`
`==> ALLONE (11:22:41:73: parseData function called`
`CID: 7161`
`==> ALLONE (11:22:41:73: Response to discovery received. Index is: -1`

This block of lines keeps then appearing in intervals, about once per minute. I really don't know anything about coding ninja blocks, udp ports or such yet, but looking into the code I figured the reason index is -1 is because the message does not contain a valid MAC address (starting with "accf"), but I don't know why this is so.

If i try to push the button on Allone, I get a different response with a macaddress found, but after that it also crashes the test code.

`==> ALLONE (11:29:1:46: Client socket: Message received from: 192.168.1.85. Message is: 686400176469accf232aef0a2020202020200000000000`
`Message received from: 192.168.1.85. Was: 686400176469accf232aef0a2020202020200000000000`
`==> ALLONE (11:29:1:46: parseData function called`
`CID: 6469`
`==> ALLONE (11:29:1:46: Button pressed packet received for index: -1`
`Button was pressed on Orvibo: -1`
`Sending this raw thing ..`
`==> ALLONE (11:29:1:47: Send message function called`
`==> ALLONE (11:29:1:48: Sent message. Error message (if present): null`
`dgram.js:367`
`    throw errnoException(err, 'getsockname');`
`          ^`
`Error: getsockname EINVAL`
`    at exports._errnoException (util.js:746:11)`
`    at Socket.address (dgram.js:367:11)`
`    at OrviboAllOne.<anonymous> (/Users/mikkoville/helloNinja/ninja-allone-master/lib/allone.js:238:65)`
`    at SendWrap.afterSend [as oncomplete] (dgram.js:348:8)`

I would really love to get this thing running, and also learn to code it more myself, but at the moment I'm quite clueless about what's causing the issue. Someone mentioned that there might be differences in node.js versions. I'm running node.js version 0.12.2, but I'm sure I can downgrade it if necessary. 

Best regards,
Mikko

**Comment by Grayda** [comment]
The fact that you can put the AllOne into LEARN mode suggests that the driver is finding the AllOne, but something is stopping it from showing the code in the text box.

Can you try putting the AllOne into learning mode on the dashboard, then press the gear icon on the red button and click "Info"? If you see your IR code in there, then it's sending the IR code to the wrong widget -- something I can fix.

And as for running the code on your Mac, later versions of node should work fine (My version of Node is the same). Can you try stopping and starting the code again? Sometimes it takes 3-4 tries for it to detect the devices.

**Comment by mvaljento** [comment]
Grayda, thank you for the prompt reply! 

I tried running the code (and other tests) multiple times, but it always seems to behave the same way: it waits for about a minute and then gives the same repeating responses.

As you instructed, I put the device into learning mode on the dashboard and took screenshots of info on the red button, info on the text input and repeated the same thing after sending an IR code to the Allone from my remote control while it was in the learning mode. Here are the screenshots:

[Red button info while in learning mode]
(https://www.dropbox.com/s/beyczrkvyihytza/Screenshot%202015-04-25%2013.52.18.jpg?dl=0)

[Text input info while in learning mode]
(https://www.dropbox.com/s/3w3ttzcs2uckn6b/Screenshot%202015-04-25%2013.52.25.jpg?dl=0)

[Red button info after receiving IR code from remote]
(https://www.dropbox.com/s/fgrh0drt7722vkf/Screenshot%202015-04-25%2013.54.14.jpg?dl=0)

[Text input info after receiving IR code from remote]
(https://www.dropbox.com/s/fpznc36kgvqb45o/Screenshot%202015-04-25%2013.54.18.jpg?dl=0)

Thanks again.

**Comment by Grayda** [comment]
That's also strange. The "Last Data" shows the IR code, so I don't know why it's not showing up in the text box. Do you have AdBlock (or another ad blocking extension) installed in your browser? Can you try adding a.ninja.is to the list of allowed sites? Does it do the same thing in another browser (e.g. Internet Explorer)?

I don't have my block (Pi Crust) plugged in any more, so I'm unable to easily test this myself.

When you run the tests manually, they're supposed to find sockets and AllOnes within seconds of starting up. At times I've had to Ctrl+C and re-run like 8-9 times before I see anything, but it's interesting to see that you're still not finding anything, despite the Ninja code and the tests using the exact same library.

If this doesn't work, then the next step will be ramping up logging to see what's going on.

**Comment by mvaljento** [comment]
Thanks for the help. I don't know what was wrong, but I rebooted everything and I'm now getting an immediate response from Allone. The text input is still not updating, but since I can copy paste the IR codes from the Info window, it doesn't matter. Managed to make my first rules to power up my amplifier by pressing the button on Allone. Yay!

Thanks again for the help. I'll start looking into writing actual code to customize the button functionality.

**Comment by mvaljento** [comment]
An issue I ran into now is that I can send the IR signals to my devices by creating rules in the Dashboard, but when I use the same codes in the button event handler in test.js, nothing happens.

Here's the code (AMP_VOL_UP code is copied from Dashboard) and ip address seems to be correct.

`o.on('buttonpress', function(index) {`
`    c("Button was pressed on Orvibo: " + index);`
`    c("Sending this raw thing ..");`
`    o.sendMessage(o.hex2ba(AMP_VOL_UP), o.hosts[index].ipaddress);`
`});`

And this is the output:

`==> ALLONE (19:23:14:467: Client socket: Message received from: 192.168.1.85. Message is: 686400176469accf232aef0a2020202020200000000000`
`Message received from: 192.168.1.85. Was: 686400176469accf232aef0a2020202020200000000000`
`==> ALLONE (19:23:14:468: parseData function called`
`CID: 6469`
`==> ALLONE (19:23:14:469: Button pressed packet received for index: 0`
`Button was pressed on Orvibo: 0`
`Sending this raw thing ..`
`==> ALLONE (19:23:14:492: Send message function called`
`==> ALLONE (19:23:14:501: Sent message. Error message (if present): null`
`Sending message to 192.168.1.85 from 192.168.1.165. Message is: `
`00000000a00000000000000000009000c0227a11160221022f028806160288061102430216022`
`4022f02220210024202170287061102900630028806170223022f028806170224022f028706170`
`28806100243021702870611024202170224022f0287061802870610024402160223023002210`
`2100243021702870610029006300222020f0243021702880610029006300287061802ff9ad422`
`ae083002000`

**Comment by Grayda** [comment]
Yep, your code won't send because it's missing the header (the 6864... bit that tells the AllOne it's a command). To fix this, try replacing the line under the "Sending this raw thing" with:

`o.emitIR(index, "00000000a00000000000000000009000c0227a11160221022f0288061602880611024302160224022f02220210024202170287061102900630028806170223022f028806170224022f02870617028806100243021702870611024202170224022f02870618028706100244021602230230022102100243021702870610029006300222020f0243021702880610029006300287061802ff9ad422ae083002000");`

This will send the IR code to the AllOne with the proper information (which is 6864 + length of the whole message in hex + 6963 (hex for "ic" (Infrared Control)) + your AllOne's UUID (MAC + padding) + 65000000 + a random value (e.g. C2) + another random value (to ensure we're not accidentally emitting IR twice) + the length of the IR message in hex + the IR message)

**Comment by mvaljento** [comment]
Ah, so I was using a wrong function there. The emitIR works!

Thanks so much for taking the time to help!

**Comment by professionalssoft** [comment]
I want to know where I put these codes and what are the tools and user steps also. Please attention to the subject

**Comment by Grayda** [comment]
Hi @professionalssoft, this particular repo is for the Ninja Block driver which isn't really supported any more (due to the uncertainty of the Ninja Blocks company and servers). If you're looking to control an AllOne or S10 / S20 WiFi socket, you'll want to use [node-orvibo](http://github.com/Grayda/node-orvibo) which you can install via npm (e.g. `npm install --save node-orvibo`) and use in your project like any other library.

https://github.com/Grayda/node-orvibo/tree/master/examples/basic has a complete example on how to use the library. If you're having troubles using the library, open up a new issue on node-orvibo instead of this repo, and I'll try and help out.

**Comment by professionalssoft** [comment]
First I like to thank you. I have allone device, Plug S20 and I will know where these codes are placed where it is extracted and whether programs to control it .arad no more details. thank you

  On Thu, Jan 21, 2016 at 5:27 AM, David Graynotifications@github.com wrote:  
Hi @professionalssoft, this particular repo is for the Ninja Block driver which isn't really supported any more (due to the uncertainty of the Ninja Blocks company and servers). If you're looking to control an AllOne or S10 / S20 WiFi socket, you'll want to use node-orvibo which you can install via npm (e.g. npm install --save node-orvibo) and use in your project like any other library.

https://github.com/Grayda/node-orvibo/tree/master/examples/basic has a complete example on how to use the library. If you're having troubles using the library, open up a new issue on node-orvibo instead of this repo, and I'll try and help out.

**Comment by Grayda** [comment]
@professionalssoft Hi, I'm not entirely sure what you're after, but suspect you might need some help setting up node.js.

Have a look at: http://www.tutorialspoint.com/nodejs/nodejs_environment_setup.htm to get started with node.js, and run `npm install node-orvibo` to download my code. Go into `examples/basic` in my node-orvibo folder (e.g. `cd examples/basic`) and run `node index.js` to run the basic example.

**If you need any more help, please open a new issue on [node-orvibo](http://github.com/grayda/node-orvibo). Please read the [node.js tutorials on TutorialsPoint](http://www.tutorialspoint.com/nodejs/index.htm) first so you understand what my code does and how you can use it**

EDIT: https://www.codecademy.com/ also has node.js tutorials, and in other languages too (e.g. if you speak Hindi or Italian or a language that is not English)

**Comment by professionalssoft** [comment]
Hi David and How are you?
At first I liked to thank you very much for helping me although I am in the new site programmers, but I appreciate your efforts and thank you. In the beginning, I tell you I am average in English language and I hope that is not lost to meI got the device was allone code download and I do not want to editing these codes at all. I just want to know where I put code in the HF-LPB100-1 and how they are programmed, as well as what programs are used to put the code on this CARD. And also I want Codes own S20.Thank you very much

  On Fri, Jan 22, 2016 at 2:34 AM, David Graynotifications@github.com wrote:  
@professionalssoft Hi, I'm not entirely sure what you're after, but suspect you might need some help setting up node.js.

Have a look at: http://www.tutorialspoint.com/nodejs/nodejs_environment_setup.htm to get started with node.js, and run npm install node-orvibo to download my code. Go into examples/basic and run node index.js to run the basic example.

If you need any more help, please open a new issue on node-orvibo. Please read the node.js tutorials on TutorialsPoint first so you understand what my code does and how you can use it

**Comment by Grayda** [comment]
Hi @professionalssoft, this code is for a computer only, and you can not put this code on the HF-LPB100 chip. As I said in my first email to you, if you want the code that is on the HF-LPB100 chip, you will need to open the chip and get the code, or talk to the company that made the chip (http://www.hi-flying.com/)

If you are looking for what commands to send to the chip, have a look here: http://www.hi-flying.com/downloadsfront.do?method=picker&flag=all&id=dc406e44-84ec-4be1-ab11-a4ce403f6d3f&fileId=0f147d14-d0aa-4fc8-b01f-36e43418d19d

If you need help with my node.js code, **please [open a new issue](https://help.github.com/articles/creating-an-issue/) on GitHub**

**Comment by professionalssoft** [comment]
Hi David I need answer?How extract this codes from Devices and what the programs used this operation?

  On Sun, Jan 24, 2016 at 4:45 AM, David Graynotifications@github.com wrote:  
Hi @professionalssoft, this code is for a computer only, and you can not put this code on the HF-LPB100 chip. As I said in my first email to you, if you want the code that is on the HF-LPB100 chip, you will need to open the chip and get the code, or talk to the company that made the chip (http://www.hi-flying.com/)

If you are looking for what commands to send to the chip, have a look here: http://www.hi-flying.com/downloadsfront.do?method=picker&flag=all&id=dc406e44-84ec-4be1-ab11-a4ce403f6d3f&fileId=0f147d14-d0aa-4fc8-b01f-36e43418d19d

If you need help with my node.js code, please open a new issue on GitHub

**Comment by Grayda** [comment]
@professionalssoft I don't know how to get the code off the device / chip. That's something you will need to learn and do, as that doesn't relate to my code.

Ask around in some disassembly forums or buy some books to read up on it, as it involves desoldering chips, plugging them into a chip programmer and lots of work.

If you want to know what codes are used to control the devices, see https://github.com/Grayda/node-orvibo/blob/master/PROTOCOL.md or disassemble the Orvibo WiWo app. But I cannot give you support for disassembling chips or the WiWo app.
